name: Katalon Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  katalon-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Katalon Tests using Docker
        env:
          KATALON_API_KEY: ${{ secrets.KATALON_API_KEY }}
        run: |
          docker run --rm -v $PWD:/katalon/katalon/source:rw \
          -e KATALON_API_KEY=$KATALON_API_KEY \
          katalonstudio/katalon \
          katalonc -noSplash -runMode=console \
          -projectPath="/katalon/katalon/source/Automation-Test.prj" \
          -retry=0 \
          -testSuitePath="Test Suites/BCO end to end" \
          -browserType="Chrome" \
          -executionProfile="default" \
          --config -webui.autoUpdateDrivers=true
